"""Create HitTrax tables

Revision ID: 474116488446
Revises: 
Create Date: 2024-12-18 23:26:49.487082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '474116488446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_feet', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weight_lbs', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('home_town', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hittrax_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('stadium', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.Integer(), nullable=True),
    sa.Column('max_pitch_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_exit_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_pitch_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_exit_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_elevation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_distance_feet', sa.Integer(), nullable=True),
    sa.Column('max_distance_feet', sa.Integer(), nullable=True),
    sa.Column('pitch_count', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('singles', sa.Integer(), nullable=True),
    sa.Column('doubles', sa.Integer(), nullable=True),
    sa.Column('triples', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('foul_balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('batting_avg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('slugging', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ld_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fb_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gb_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hittrax_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('distance_feet', sa.Integer(), nullable=True),
    sa.Column('pitch_vel_mph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('play_type', sa.Integer(), nullable=True),
    sa.Column('fielder', sa.Integer(), nullable=True),
    sa.Column('quadrant', sa.Integer(), nullable=True),
    sa.Column('pitch_type', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ground_distance_feet', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['hittrax_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('plays')
    op.drop_table('session')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unitid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stadium', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('skilllevel', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('gametype', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('role', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('position', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bats', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('throws', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hometown', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graduationyear', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('birthdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('session',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unitid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stadium', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('skilllevel', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('gametype', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('maxpitchvel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maxexitvel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avgpitchvel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avgexitvel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avgelevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avgdistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maxdistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pitchcount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('hitcount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('singles', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('doubles', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('triples', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('homeruns', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('foulballs', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('strikes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('balls', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('strikezonewidth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('plays',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sessionid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exitballvel1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exitballvel2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exitballvel3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pitchvel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('result', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fielder', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quadrant', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pitchtype', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grounddist', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('active', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('exitvelo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('points', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('hittrax_plays')
    op.drop_table('hittrax_sessions')
    op.drop_table('athletes')
    # ### end Alembic commands ###
